
// Mock Data for QC Beats Management - Dense Hyderabad Dataset

export const mockBeats = [
    // --- MAIN ROADS AROUND HUSSAIN SAGAR ---
    {
        id: "BT-101",
        name: "Tank Bund Road - North",
        ward: "Ward 1",
        zone: "Central Zone",
        shift: "Morning", // 6AM - 2PM
        status: "Cleaned",
        coordinates: [[17.4239, 78.4738], [17.4146, 78.4754]], // Tank Bund
        color: "#16a34a", // Green
        lastCleaned: "Today, 8:30 AM",
        assignedTo: "Ramesh Gupta",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-102",
        name: "Tank Bund Road - South",
        ward: "Ward 1",
        zone: "Central Zone",
        shift: "Morning",
        status: "Partially covered",
        coordinates: [[17.4146, 78.4754], [17.4082, 78.4760]], // Tank Bund cont.
        color: "#ca8a04", // Amber
        lastCleaned: "Today, 9:15 AM",
        assignedTo: "Suresh Kumar",
        reason: "Vehicle obstruction on left lane",
        actionPlanned: "Reschedule for afternoon",
        actionStatus: "Pending",
        timeIdentified: "2h ago",
        slaBreach: false
    },
    {
        id: "BT-103",
        name: "Necklace Road - West Stretch",
        ward: "Ward 2",
        zone: "Central Zone",
        shift: "Morning",
        status: "Cleaned",
        coordinates: [[17.4268, 78.4655], [17.4190, 78.4680]],
        color: "#16a34a",
        lastCleaned: "Today, 7:45 AM",
        assignedTo: "Venkat Reddy",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-104",
        name: "Necklace Road - PV Ghat",
        ward: "Ward 2",
        zone: "Central Zone",
        shift: "Night",
        status: "Not cleaned",
        coordinates: [[17.4190, 78.4680], [17.4120, 78.4650]],
        color: "#dc2626", // Red
        lastCleaned: "Yesterday",
        assignedTo: "Rajesh Singh",
        reason: "Manpower shortage",
        actionPlanned: "Deploy reserve team",
        actionStatus: "Pending",
        timeIdentified: "4h ago",
        slaBreach: true
    },
    {
        id: "BT-105",
        name: "Khairatabad Flyover",
        ward: "Ward 3",
        zone: "West Zone",
        shift: "Morning",
        status: "Cleaned",
        coordinates: [[17.4120, 78.4650], [17.4080, 78.4620]],
        color: "#16a34a",
        lastCleaned: "Today, 6:30 AM",
        assignedTo: "M. Krishna",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },

    // --- SECUNDERABAD AREA ---
    {
        id: "BT-201",
        name: "RP Road - Stretch A",
        ward: "Ward 5",
        zone: "North Zone",
        shift: "Morning",
        status: "Cleaned",
        coordinates: [[17.4350, 78.4950], [17.4380, 78.5000]],
        color: "#16a34a",
        lastCleaned: "Today, 8:00 AM",
        assignedTo: "P. Sharma",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-202",
        name: "RP Road - Stretch B",
        ward: "Ward 5",
        zone: "North Zone",
        shift: "Morning",
        status: "Not cleaned",
        coordinates: [[17.4380, 78.5000], [17.4410, 78.5050]],
        color: "#dc2626",
        lastCleaned: "Yesterday",
        assignedTo: "L. Yadav",
        reason: "Construction debris blocking road",
        actionPlanned: "Coordinate with engineering",
        actionStatus: "In Progress",
        timeIdentified: "1h ago",
        slaBreach: false
    },
    {
        id: "BT-203",
        name: "MG Road Main",
        ward: "Ward 5",
        zone: "North Zone",
        shift: "Night",
        status: "Cleaned",
        coordinates: [[17.4300, 78.4850], [17.4350, 78.4900]],
        color: "#16a34a",
        lastCleaned: "Today, 4:00 AM",
        assignedTo: "K. Rao",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },

    // --- HIMAYATNAGAR / LIBERTY ---
    {
        id: "BT-301",
        name: "Liberty Circle to Himayatnagar",
        ward: "Ward 8",
        zone: "Central Zone",
        shift: "Morning",
        status: "Cleaned",
        coordinates: [[17.4050, 78.4800], [17.4000, 78.4820]],
        color: "#16a34a",
        lastCleaned: "Today, 7:15 AM",
        assignedTo: "V. Kumar",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-302",
        name: "Himayatnagar Main Road",
        ward: "Ward 8",
        zone: "Central Zone",
        shift: "Morning",
        status: "Not cleaned",
        coordinates: [[17.4000, 78.4820], [17.3950, 78.4840]],
        color: "#dc2626",
        lastCleaned: "Yesterday",
        assignedTo: "D. Srinivas",
        reason: "Sweeper absent",
        actionPlanned: "Assign substitute",
        actionStatus: "Pending",
        timeIdentified: "3h ago",
        slaBreach: true
    },
    {
        id: "BT-303",
        name: "Narayanguda Cross Road",
        ward: "Ward 8",
        zone: "Central Zone",
        shift: "Afternoon",
        status: "Partially covered",
        coordinates: [[17.3950, 78.4840], [17.3900, 78.4860]],
        color: "#ca8a04",
        lastCleaned: "Today, 1:00 PM",
        assignedTo: "A. Pasha",
        reason: "Heavy traffic congestion",
        actionPlanned: "Review during night shift",
        actionStatus: "Resolved",
        timeIdentified: "30m ago",
        slaBreach: false
    },

    // --- BANJARA HILLS ---
    {
        id: "BT-401",
        name: "Road No 1",
        ward: "Ward 10",
        zone: "West Zone",
        shift: "Morning",
        status: "Cleaned",
        coordinates: [[17.4150, 78.4500], [17.4200, 78.4450]],
        color: "#16a34a",
        lastCleaned: "Today, 6:00 AM",
        assignedTo: "Sarah J",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-402",
        name: "Road No 12",
        ward: "Ward 10",
        zone: "West Zone",
        shift: "Morning",
        status: "Not assigned",
        coordinates: [[17.4100, 78.4400], [17.4150, 78.4450]],
        color: "#94a3b8", // Grey
        lastCleaned: "N/A",
        assignedTo: "Unassigned",
        reason: "New route added",
        actionPlanned: "Assign in next roster",
        actionStatus: "Pending",
        timeIdentified: "1d ago",
        slaBreach: false
    },
    {
        id: "BT-403",
        name: "KBR Park Perimeter",
        ward: "Ward 12",
        zone: "West Zone",
        shift: "Morning",
        status: "Cleaned",
        coordinates: [[17.4250, 78.4200], [17.4300, 78.4250]],
        color: "#16a34a",
        lastCleaned: "Today, 5:30 AM",
        assignedTo: "M. Ali",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-404",
        name: "Jubilee Hills Checkpost",
        ward: "Ward 12",
        zone: "West Zone",
        shift: "Morning",
        status: "Not cleaned",
        coordinates: [[17.4300, 78.4250], [17.4350, 78.4300]],
        color: "#dc2626",
        lastCleaned: "Yesterday",
        assignedTo: "T. Reddy",
        reason: "VIP Movement restriction",
        actionPlanned: "Clean post-clearance",
        actionStatus: "Pending",
        timeIdentified: "5h ago",
        slaBreach: false
    },

    // --- OLD CITY / CHARMINAR (Simulated) ---
    {
        id: "BT-501",
        name: "Madina Circle",
        ward: "Ward 20",
        zone: "South Zone",
        shift: "Night",
        status: "Cleaned",
        coordinates: [[17.3650, 78.4750], [17.3600, 78.4750]],
        color: "#16a34a",
        lastCleaned: "Today, 3:30 AM",
        assignedTo: "Md. Arif",
        reason: null,
        actionPlanned: null,
        actionStatus: null,
        timeIdentified: null,
        slaBreach: false
    },
    {
        id: "BT-502",
        name: "Charminar Road",
        ward: "Ward 20",
        zone: "South Zone",
        shift: "Night",
        status: "Partially covered",
        coordinates: [[17.3600, 78.4750], [17.3616, 78.4747]],
        color: "#ca8a04",
        lastCleaned: "Today, 4:00 AM",
        assignedTo: "S. Khan",
        reason: "Market vendors early arrival",
        actionPlanned: "Clean peripheral areas",
        actionStatus: "Resolved",
        timeIdentified: "4h ago",
        slaBreach: false
    },
];

// Mock Data for Analytics
export const dailyCoverageData = [
    { day: "09 Jan", coverage: 82 },
    { day: "10 Jan", coverage: 85 },
    { day: "11 Jan", coverage: 78 },
    { day: "12 Jan", coverage: 90 },
    { day: "13 Jan", coverage: 88 },
    { day: "14 Jan", coverage: 92 },
    { day: "15 Jan", coverage: 87 },
];
